mensajeria:
  driver: postgresql
  host: localhost
  port: 5432
  user: postgres
  password: Ec94
  db: proyecto

bodega:
  driver: postgresql+psycopg2
  host: localhost
  port: 5432
  user: postgres
  password: Ec94
  db: proyectob